### ISSUE TITLE
Laplacian of the displacement

### ISSUE THREAD

**Issue by Yishun99** [rgl-epfl/large-steps-pytorch#18]
Hi , I am working on baking displacement map via a differentiable learning framework.
And I wonder if the LargeStep method can be used for achieving better results.
However, things come with different since I only want to learn scalar displacement instead of the 3-dim position per vertex.
Generally speaking, is it possible to apply the LargeStep method on more geometry parameters, such as displacement, normal, and/or mix of them?

**Comment by bathal1** [comment]
Hi,

The Laplacian can be applied to any function that takes values at every vertex. That function can be scalar-valued (e.g. displacement, roughness), or vector-valued (e.g. position, color). If you define displacement per-vertex, then you should be able to use this approach.

Note that you can also use it for a texture, by defining the appropriate graph Laplacian for a regular 2D grid.

**Comment by Yishun99** [comment]
Hi, 
Thank you!
Because of the constraint is applied on the vertex (only the displacement along normal direction is allowed), I have to define the optimizer upon raw vertices, instead of the parameterization _u_. 
And thus the pre-conditioned update rule that working on _u_ is no longer applicable. 
How can we enjoy the "further quality improvements" bring from "learning on such reparameterized coordinates _u_"?

**Comment by bathal1** [comment]
The parameterization can be applied to any function defined on vertices. In pseudocode, you could do something like this:

```python
L = get_mesh_laplacian(v, f)
diff_displacement = to_differential(displacement)
torch.enable_grad(diff_displacement)

for it in range(n_steps):
    displacement = from_differential(diff_displacement)
    v = apply_displacement(v, displacement)

    img= render()

   ...
```

This would be fine, since the optimizer handles the variables being optimised. In this case this would be the (differential) displacement, not the vertex positions.

Please have a look at the tutorial on the [large-steps-pytorch](https://github.com/rgl-epfl/large-steps-pytorch/blob/master/Tutorial.ipynb) repo  or Mitsuba 3's [shape optimization tutorial](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/shape_optimization.html) to get an idea of how it would work.

**Comment by Yishun99** [comment]
Thank you very much!
The LargeStep has been successfully integrated into our shape&texture baking framework.
